# Generated by Django 4.0.6 on 2022-11-25 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='welcome_to_admin',
            old_name='informtion',
            new_name='information',
        ),
    ]
